# Generated by Django 3.2.1 on 2021-08-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brand_category_id',
        ),
        migrations.DeleteModel(
            name='brand',
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
