# Generated by Django 3.2.2 on 2021-09-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_slider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='slider',
            new_name='sliderr',
        ),
    ]
