# Generated by Django 3.2.1 on 2021-09-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_rename_slider_sliderr'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannerr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_text', models.CharField(max_length=100)),
                ('banner_image', models.CharField(max_length=500)),
            ],
        ),
    ]
