# Generated by Django 3.2.2 on 2021-09-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_addprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addprod',
            name='size_footwears',
        ),
    ]
