# Generated by Django 3.2.2 on 2021-10-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_addfootwear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfootwear',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.brand'),
        ),
        migrations.AlterField(
            model_name='addfootwear',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category'),
        ),
        migrations.AlterField(
            model_name='addprod',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.brand'),
        ),
        migrations.AlterField(
            model_name='addprod',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category'),
        ),
    ]
