# Generated by Django 3.2.2 on 2021-10-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_auto_20211013_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addfootwear',
        ),
    ]
