# Generated by Django 3.2.2 on 2021-10-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_delete_addfootwear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addprod',
            old_name='image',
            new_name='imagee',
        ),
        migrations.CreateModel(
            name='addfootwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=30)),
                ('size_foot', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=500)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
            ],
        ),
    ]
