# Generated by Django 3.2.2 on 2021-10-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_auto_20211018_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addfootwear',
            name='image',
        ),
        migrations.RemoveField(
            model_name='addprod',
            name='imagee',
        ),
        migrations.RemoveField(
            model_name='prod_image',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='prod_image',
            name='category',
        ),
    ]
