# Generated by Django 3.2.1 on 2021-08-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='loggin',
        ),
    ]
