# Generated by Django 3.2.1 on 2021-08-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_login_loggin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loggin',
        ),
        migrations.DeleteModel(
            name='signupp',
        ),
    ]
