# Generated by Django 3.2.2 on 2021-08-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_loggin_signupp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='signupp',
            name='mobilenumber',
            field=models.IntegerField(max_length=20),
        ),
    ]
