# Generated by Django 3.2.1 on 2021-08-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_loggin_signupp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupp',
            name='email',
        ),
        migrations.AlterField(
            model_name='loggin',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
