# Generated by Django 3.2.1 on 2021-08-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_signupp_mobilenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggin',
            old_name='email',
            new_name='mobilenumber',
        ),
        migrations.RenameField(
            model_name='signupp',
            old_name='mobilenumber',
            new_name='email',
        ),
    ]
