# Generated by Django 3.2.1 on 2021-08-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_auto_20210806_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupp',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
