# Generated by Django 3.2.1 on 2021-08-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_signupp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggin',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
