# Generated by Django 3.2.1 on 2021-08-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_loggin_mobilenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loggin',
        ),
    ]
