# Generated by Django 3.2.2 on 2021-09-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_alter_loggin_mobilenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggin',
            name='user_id',
        ),
    ]
