# Generated by Django 3.2.2 on 2021-09-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_remove_loggin_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggin',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.signupp'),
            preserve_default=False,
        ),
    ]
